name: pi_task_watch
description: "PI Task Watch - Employee monitoring application with Odoo integration"
publish_to: "none"

version: 1.0.23+23

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  window_size: ^0.1.0
  rust_lib_pi_task_watch:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  logarte: ^0.2.3
  screen_capturer: ^0.2.3
  path_provider: ^2.1.1

  # connectivity_plus: ^3.0.3  # For network connectivity detection
  # flutter_secure_storage: ^8.0.0  # For secure storage of sensitive data
  logger: ^1.3.0 # For better logging
  uuid: ^3.0.7
  http: ^1.3.0
  flutter_easyloading: ^3.0.5
  window_to_front: ^0.0.3
  system_tray: ^2.0.3
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  collection: ^1.19.1
  flutter_spinkit: ^5.2.1
  dio: ^5.9.0
  wakelock_plus: ^1.4.0  # Keep app active during system sleep/idle

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  icons_launcher: ^2.0.0
  rename: ^2.1.1
  fastforge: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/


# flutter_rust_bridge_codegen generate --watch
# fastforge package --platform macos --targets dmg
# fastforge package --platform windows --targets exe
# fastforge package --platform linux --targets deb
