app_id: 6D31B782-F721-4EC5-9F8A-29D53F92C4B1
publisher: Primacy Infotech
publisher_url: https://primacyinfotech.com
display_name: PI Task Watch
create_desktop_icon: true
# setup_icon_file: windows/runner/resources/app_icon.ico
locales:
  - en
# script_template: custom_setup.iss
